# Generated by Django 3.2.18 on 2023-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('booknum', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
