# Generated by Django 4.1.7 on 2023-03-22 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("bookid", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("booknum", models.IntegerField()),
                ("description", models.TextField()),
                ("bookpic", models.TextField(default="undefined")),
                ("bookcategory", models.TextField(default="undefined")),
            ],
            options={
                "db_table": "Book",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("rentno", models.IntegerField(primary_key=True, serialize=False)),
                ("borrow_date", models.DateTimeField(auto_now_add=True)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("rent_deadline", models.DateTimeField(blank=True, null=True)),
                ("rent_sts", models.BooleanField(default=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Record",
            },
        ),
    ]
