# Generated by Django 4.1.7 on 2023-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="bookcategory",
            field=models.TextField(default="undefined"),
        ),
        migrations.AddField(
            model_name="book",
            name="bookpic",
            field=models.TextField(default="undefined"),
        ),
        migrations.AddField(
            model_name="record",
            name="rent_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="rent_sts",
            field=models.BooleanField(default=True),
        ),
    ]
