# Generated by Django 4.1.7 on 2023-03-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_userprofile_alter_record_user_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
